### ISSUE TITLE
[BUG] /status/{ticket} returns internal server error

### ISSUE THREAD

**Issue by jkouvar** [OpertusMundi/profile#4]
**Description**

Until release [1.0.0-rc.5](https://github.com/OpertusMundi/profile/releases/tag/1.0.0-rc.5), endpoint [/status/{ticket}](https://opertusmundi.github.io/profile/#/Status/getStatus) was returning the job status.

After the latest release, an internal server error is returned. The following data is logged by the profile service:

```
profile_1  | 2021-07-29 15:00:08,434 - geoprofile - INFO - Processing of ticket: afeb7622-2559-4d5a-95df-7eab9938ee35 is completed successfully
profile_1  | [2021-07-29 15:01:35 +0000] [28] [ERROR] Error handling request /status/afeb7622-2559-4d5a-95df-7eab9938ee35
profile_1  | Traceback (most recent call last):
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 136, in handle
profile_1  |     self.handle_request(listener, req, client, addr)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 179, in handle_request
profile_1  |     respiter = self.wsgi(environ, resp.start_response)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2069, in __call__
profile_1  |     return self.wsgi_app(environ, start_response)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2054, in wsgi_app
profile_1  |     response = self.handle_exception(e)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
profile_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2051, in wsgi_app
profile_1  |     response = self.full_dispatch_request()
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1501, in full_dispatch_request
profile_1  |     rv = self.handle_user_exception(e)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
profile_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in full_dispatch_request
profile_1  |     rv = self.dispatch_request()
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1485, in dispatch_request
profile_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/geoprofile-1.0.0-py3.8.egg/geoprofile/app.py", line 2705, in status
profile_1  |     return make_response({"completed": bool(results['status']), "success": success,
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/helpers.py", line 187, in make_response
profile_1  |     return current_app.make_response(args)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1699, in make_response
profile_1  |     rv = jsonify(rv)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 348, in jsonify
profile_1  |     f"{dumps(data, indent=indent, separators=separators)}\n",
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 129, in dumps
profile_1  |     rv = _json.dumps(obj, **kwargs)
profile_1  |   File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
profile_1  |     return cls(
profile_1  |   File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
profile_1  |     chunks = list(chunks)
profile_1  |   File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
profile_1  |     yield from _iterencode_dict(o, _current_indent_level)
profile_1  |   File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
profile_1  |     yield from chunks
profile_1  |   File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
profile_1  |     o = _default(o)
profile_1  |   File "/usr/local/lib/python3.8/dist-packages/geoprofile-1.0.0-py3.8.egg/geoprofile/app.py", line 40, in default
profile_1  |     return super(JSONEncoder, self).default(obj)
profile_1  |   File "/usr/lib/python3.8/json/encoder.py", line 179, in default
profile_1  |     raise TypeError(f'Object of type {o.__class__.__name__} '
profile_1  | TypeError: Object of type datetime is not JSON serializable
profile_1  | 192.168.1.100 - - [29/Jul/2021:15:01:35 +0000] "GET /status/afeb7622-2559-4d5a-95df-7eab9938ee35 HTTP/1.1" 500 0 "-" "-"
```

**Comment by pmitropoulos** [comment]
Fixed with 2aeb1bce4998fa0590f97148be83540bfab019de
